spring:
  application:
    name: train_ticket_management

  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/train_ticket_db
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true